djangonautic/account/urls.py
from django.urls import path , re_path
from . import views

app_name='account'

urlpatterns = [
    path('signup/',views.signup_veiw,name="signup"),
    path('login/',views.login_veiw,name="login"),
    path('logout/',views.logout_veiw,name="logout")
]

djangonautic/articles/urls.py
from django.urls import path , re_path
from . import views

app_name='articles'

urlpatterns = [
    path('',views.article_list,name="list"),
    path('create/',views.article_create,name="create"),
    re_path('(?P<slug>[\w-]+)/', views.article_details,name="details")
]

djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/',views.about),
    path('',article_views.article_list,name="home"),
    path('articles/',include('articles.urls')),
     path('account/',include('account.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

djangonautic/account/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# Model for the article data
class Article(models.Model):
    title=models.CharField( max_length=100)
    slug=models.SlugField()
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    thumb=models.ImageField(default='default.png',blank=True)
    author=models.ForeignKey(User,default=None,on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

djangonautic/articles/forms.py
from django import forms
from .  import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model=models.Article
        fields=['title','body','slug','thumb']

djangonautic/account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
#sign up view
def signup_veiw(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            #login the user
            login(request,user)
            return redirect('articles:list')
    else:
        form=UserCreationForm()
    
    return render(request,'account/signup.html',{'form':form})

#login view
def login_veiw(request):
    if request.method=='POST':
         form=AuthenticationForm(data=request.POST)
         if form.is_valid():
             #login the user
             user=form.get_user()
             login(request,user)
             if 'next' in request.POST:
                return redirect(request.POST.get('next'))
             else:
                return redirect('articles:list')
    else:
        form=AuthenticationForm()

    return render(request,'account/login.html',{'form':form})

#log out view
def logout_veiw(request):
    if request.method=='POST':
        logout(request)
        return redirect('articles:list')

djangonautic/articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(request):
    articles=Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles':articles})

def article_details(request,slug):
    article=Article.objects.get(slug=slug)
    return render(request,'articles/article_details.html',{'article':article})

# def article_details(request, slug):
#     return HttpResponse(slug)

@login_required(login_url="/account/login/")
def article_create(request):
    if request.method=='POST':
        form=forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            #save the form to db
            instance=form.save(commit=False)
            instance.author=request.user
            instance.save()
            return redirect('articles:list')
    else:
        form=forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})

djangonautic/djangonautic/views.py
from django.http  import HttpResponse
from django.shortcuts import render

def homepage(request):
   #return HttpResponse("About page")
   return render(request,'homepage.html')

def about(request):
    #return HttpResponse("HomePage") 
    return render(request,'about.html')

djangonautic/articles/templates/articles/article_create.html
{%extends 'base_layout.html'%}

{%block content%}
    <div class="create-article">
        <h2>Create Article here</h2>
        <form class="site-form" action="{%url 'articles:create'%}" method="post" enctype="multipart/form-data"> 
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Create">
        </form>
    </div>
{%endblock%}

djangonautic/articles/templates/articles/article_details.html
{%extends 'base_layout.html'%}

{%block content%}
<div class="article-detail">
    <div class="article">
        <h1>Articles Details</h1>
            <img src="{{article.thumb.url}}" />
            <h2>{{article.title}}</h2>
            <hr>
            <p>{{article.body}}</p>
            <p>{{article.date}}</p>

    </div>
</div>
{%endblock%}

djangonautic/articles/templates/articles/article_list.html
{%extends 'base_layout.html'%}

{%block content%}
<h1>Articles List</h1>
<div class="articles">
    {% for i in articles%}
    <div class="article">
        <h2><a href="{% url 'articles:details' slug=i.slug %}">{{i.title}}</a></h2>
        <p>{{i.snippet}}</p>
        <p>{{i.date}}</p>
        <p>Author name: {{i.author.username}}</p>
    </div>
    {% endfor %}
</div>
{%endblock%}

djangonautic/templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="wrapper">
    <h1>About Us</h1>
    <p>We like django.</p>
</div>
{% endblock %}

djangonautic/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Articles</title>
        {% comment %} <link rel="stylesheet" href="{%static 'index.css'%}" /> {% endcomment %}
    </head>
    <body>
        <header class="wrapper">
            <h1><u><b>Ashish Blog World</u></b></h1>
            <nav>
                <ul>
                {%if user.is_authenticated%}
                    <li>
                        <form class="logout-link" action="{%url 'account:logout'%}" method="post">
                            {% csrf_token %}
                            <button type="submit">LogOut</button>
                        </form>
                    </li>
                    <li><a href="{%url 'articles:create'%}" class="highlight">New Artcile</a></li>
                {%else%}
                    <li><a href="{%url 'account:login'%}">Login</a></li>
                    <li><a href="{%url 'account:signup'%}">Sign Up</a></li>
                {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>